spring:
  cloud:
    gateway:
      routes:
      - id: service-products
        uri: lb://service-products
        predicates:
          - Path=/api/v1/products/**
        filters:
          - StripPrefix=3
          - ExampleCookie=Hola,usuario,JhovinBonifacio
      - id: service-items
        uri: lb://service-items
        predicates:
          - Path=/api/v1/items/**
        filters:
          - StripPrefix=3
          - AddRequestHeader=token-request, 123456
          - AddResponseHeader=token-response, 12345678
          - AddRequestParameter=name, jhovin